### ISSUE TITLE
USB 3.0 devices not detected

### ISSUE THREAD

**Issue by sreehax** [aidanchandra/x1c7-hackintosh#10]
Described in #7, most probably the cause of it

https://github.com/aidanchandra/x1c7-hackintosh/issues/7#issuecomment-797874586

**Comment by aidanchandra** [comment]
Alright just for other's seeing this issue AND to confirm
Your OS is Big Sur - correct?

I've seen no evidence on my machine to suggest USB3.0 is not working. I've used a few USB3.0 devices including flash drives and they work fine. Furthermore I've even used an EGPU (pretty nifty) and it worked fine natively with TB3.

Can you send a screenshot of your USB hackintool page?

**Comment by aidanchandra** [comment]
Oh. Major difference too - I'm on Catalina.

**Comment by sreehax** [comment]
Oh yeah I'm on Big Sur 11.2.3 on the 20QD0000US (i7-8565u). Interestingly enough I think that USB 3.0 does work if I use the USB C charging port (I think, not entirely sure), but that's about it and even that was very iffy. Here's my hackintool: 
![Screen Shot 2021-03-15 at 12 04 34](https://user-images.githubusercontent.com/23709124/111207273-a5e08a00-8586-11eb-8a61-a61027bc3743.png)

**Comment by aidanchandra** [comment]
Yup - you are injecting correctly. USB behavior should be the exact same for both of us.

This _could_ be an issue with big sur/opencore/usbInject so I don't exactly know where to go from here sadly. 

Do you have a touch screen?? Neat.

One thing of note is that your hackintool indicates that there hasn't been anything plugged into those USB ports (see the green). Try plugging things in to them while hackintool is running and see if you can at least get them all to be green.

May I ask if you're heartset on big sur or would consider going back to Catalina, even just for debugging this issue. I can imagine no USB3 would be quite annoying.

**Comment by sreehax** [comment]
Well this is really odd: now my USB 3.0 stuff is detected properly! I have no idea what I changed or whether hackintool fixed something. But now I managed to plug in stuff into every USB port possible and turned it all green (a USB SSD and OnePlus 6T (USB 2.0) in both USB A ports, a usb c to usb a adapter with a TI-84 Plus CE (definitely not 3.0 lol) plugged into the usb c port that's meant for the ethernet adapter, and a USB 8 in 1 hub in the usb c charging port. Now I'm not sure whether to verify that 3.0 speeds actually work but at least stuff doesn't go undetected anymore. I do have a thinkpad with a touch screen (only option from Costco at the time) and the touchscreen basically works like a mouse (I can tap and drag windows and the mouse cursor follows). Also I am kind of set on Big Sur since Catalina had issues with my USB C ethernet and AirportItlwm somehow
![Screen Shot 2021-03-15 at 12 23 43](https://user-images.githubusercontent.com/23709124/111211869-2a81d700-858c-11eb-97bd-1d74edd11cf0.png)

**Comment by sreehax** [comment]
![Screen Shot 2021-03-15 at 12 37 28](https://user-images.githubusercontent.com/23709124/111211100-3caf4580-858b-11eb-9f64-3686ff68fda4.png)
yeah according to this I'm getting less than the 480 Mb/s for USB 2.0, so I figure I'm getting USB 2.0 speeds. I mean it is still an improvement over when USB 3.0 devices just weren't detected

**Comment by aidanchandra** [comment]
I haven't tested my own USB3 speeds - just detection. I'll do that to ensue it's not broken on my end as well.

Also just a thing I'm realizing now - a lot of these things are 'intermittent' or solved with a clean install. In the dev. stages of this project @suhrmann and I had to clean install a few times to get behavior to, well, behave as expected. Something with the way kexts load or something is a little wonky and sometimes they get stuck. Like how the heck did bluetooth not work for me on Big Sur but it didn't work for you on Catalina.

**Comment by sreehax** [comment]
Yeah there's just some strange stuff all around. By clean install do you mean keep the opencore fully intact but install macOS fresh?

**Comment by aidanchandra** [comment]
Yeah I mean boot into Mac installer and do a clean install.

**Comment by sreehax** [comment]
I just reinstalled macOS Big Sur and funny enough the exact same issue is back. The non internal USB's are all Unknown speed in Hackintool. I can still plug in USB 2.0 devices and they go green but then USB 3.0 devices still aren't detected. I'm using the exact same EFI as before but new macOS install

**Comment by suhrmann** [comment]
Very strange...

Maybe it's a problem of the internal USB limit that is unnoticed exceeded - and Big Sur has another ordering of the USBs than Catalina?

**Comment by aidanchandra** [comment]
Yeah I'm beginning to suspect this is an issue of catalina vs big sur more so than anything EFI related. Maybe attach a short video of you going through the pertinent settings in your BIOS (I still have to add the correct BIOS configuration to the README - ugh)

**Comment by aidanchandra** [comment]
I'm going to close this. @sreehax please feel free to comment if you decide to go back to catalina to test whether or not it's an OS issue (which it likely is). 

If you get a lead, send it over too and I'll see if we can fix it. :)
